services:
  taskiq-scheduler:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    env_file:
      - .env
    volumes:
      - ../app:/app/app
    environment:
      - TZ=UTC
    restart: always
    networks:
      - web

  uvicorn-app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file:
      - .env
    volumes:
      - ../app:/app/app
    environment:
      - TZ=UTC
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`api.game.mirash.su`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
    restart: always
    networks:
      - web

  traefik:
    build:
      context: .
      dockerfile: docker/traefik/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-public-certificates:/certificates"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.learn.mirash.su`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${DASHBOARD_USER}"
    restart: always
    networks:
      - web

networks:
  web:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "${IPV6_SUBNET}"

