"""empty message

Revision ID: 2d17909d0fbf
Revises: 0e905a00cec6
Create Date: 2025-06-22 18:30:22.709372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d17909d0fbf'
down_revision: Union[str, None] = '0e905a00cec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equip_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('farm_modes')
    op.drop_column('inventories', 'active')
    op.add_column('items', sa.Column('can_equip', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('players', 'resource_multiplier')
    op.drop_column('players', 'energy_multiplier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('energy_multiplier', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('resource_multiplier', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('items', 'can_equip')
    op.add_column('inventories', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('farm_modes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_energy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_resources', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_zone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_zone_id'], ['resources_zones.id'], name=op.f('farm_modes_resource_zone_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('farm_modes_pkey'))
    )
    op.drop_table('player_stats')
    op.drop_table('equip_items')
    op.drop_table('item_stats')
    # ### end Alembic commands ###
