"""empty message

Revision ID: 3799c4c33b03
Revises: 795dd2b240c0
Create Date: 2025-02-08 15:24:55.494226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3799c4c33b03'
down_revision: Union[str, None] = '795dd2b240c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute("UPDATE inventories SET active = FALSE")
    op.alter_column('inventories', 'active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'active')
    # ### end Alembic commands ###
