"""empty message

Revision ID: 381b45052d22
Revises: e5795c11760d
Create Date: 2025-01-15 02:23:16.684504

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '381b45052d22'
down_revision: Union[str, None] = 'e5795c11760d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players_items_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('player_base_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['player_base_id'], ['players_bases.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.rename_table('players_bases_storage', 'players_resources_storage')
    op.add_column(
        'players_resources_storage',
        sa.Column('player_id', sa.Integer(), sa.ForeignKey('players.id'), nullable=True)
    )
    op.add_column('inventories', sa.Column('tier', sa.Integer(), nullable=False))
    op.drop_column('items', 'tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('inventories', 'tier')
    op.create_table('players_bases_storage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_base_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['player_base_id'], ['players_bases.id'], name='players_bases_storage_player_base_id_fkey'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='players_bases_storage_resource_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='players_bases_storage_pkey')
    )
    op.drop_table('players_resources_storage')
    op.drop_table('players_items_storage')
    # ### end Alembic commands ###
