"""empty message

Revision ID: 5b6868a4b0cd
Revises: 825c43194534
Create Date: 2025-01-02 01:41:43.356733

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5b6868a4b0cd'
down_revision: Union[str, None] = '825c43194534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('maps', sa.Column('width', sa.Integer(), nullable=True))
    op.drop_column('maps', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('maps', 'width')
    op.drop_column('maps', 'height')
    # ### end Alembic commands ###
