"""empty message

Revision ID: 67c54eec26ff
Revises: 5b6868a4b0cd
Create Date: 2025-01-06 22:59:57.314697

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '67c54eec26ff'
down_revision: Union[str, None] = '5b6868a4b0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('total_energy', sa.Integer(), nullable=False),
    sa.Column('total_resources', sa.Integer(), nullable=False),
    sa.Column('resource_zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_zone_id'], ['resources_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('players', sa.Column('energy', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('resource_multiplier', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('energy_multiplier', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('status', sa.String(), nullable=False))
    op.drop_constraint('players_bases_owner_id_fkey', 'players_bases', type_='foreignkey')
    op.create_foreign_key(None, 'players_bases', 'players', ['owner_id'], ['id'])
    op.drop_column('resources_zones', 'curren_resource_amount')
    op.drop_column('resources_zones', 'regeneration_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources_zones', sa.Column('regeneration_rate', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('resources_zones', sa.Column('curren_resource_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'players_bases', type_='foreignkey')
    op.create_foreign_key('players_bases_owner_id_fkey', 'players_bases', 'users', ['owner_id'], ['telegram_id'])
    op.drop_column('players', 'status')
    op.drop_column('players', 'energy_multiplier')
    op.drop_column('players', 'resource_multiplier')
    op.drop_column('players', 'energy')
    op.drop_table('players_resources')
    op.drop_table('farm_sessions')
    op.drop_table('farm_modes')
    op.drop_table('building_costs')
    # ### end Alembic commands ###
