"""empty message

Revision ID: 7eff3741a673
Revises: 381b45052d22
Create Date: 2025-01-15 14:57:05.727866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eff3741a673'
down_revision: Union[str, None] = '381b45052d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players_resources_storage', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    from sqlalchemy.sql import table, column, update
    players_resources_storage = table(
        'players_resources_storage',
        column('player_id', sa.Integer())
    )
    op.execute(update(players_resources_storage).values(player_id=1))
    op.alter_column('players_resources_storage', 'player_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players_resources_storage', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
