"""empty message

Revision ID: 825c43194534
Revises: 4a13285f6626
Create Date: 2025-01-02 01:24:19.242533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825c43194534'
down_revision: Union[str, None] = '4a13285f6626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'map_object_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'map_object_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
