"""empty message

Revision ID: 88cb8691a2e2
Revises: 3799c4c33b03
Create Date: 2025-02-08 20:34:09.836159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cb8691a2e2'
down_revision: Union[str, None] = '3799c4c33b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'count')
    op.drop_column('players_items_storage', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_items_storage', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inventories', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
