"""empty message

Revision ID: be4c199f24d1
Revises: 87e3c2819896
Create Date: 2025-01-14 03:37:44.073759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4c199f24d1'
down_revision: Union[str, None] = '87e3c2819896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('item_id', sa.Integer(), nullable=False))
    op.drop_constraint('inventories_resource_id_fkey', 'inventories', type_='foreignkey')
    op.create_foreign_key(None, 'inventories', 'items', ['item_id'], ['id'])
    op.drop_column('inventories', 'resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.create_foreign_key('inventories_resource_id_fkey', 'inventories', 'resources', ['resource_id'], ['id'])
    op.drop_column('inventories', 'item_id')
    # ### end Alembic commands ###
