"""str -> Datetime

Revision ID: c6bcd4c1c6ee
Revises: 5c61f8c857da
Create Date: 2025-01-13 20:04:05.457355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bcd4c1c6ee'
down_revision: Union[str, None] = '5c61f8c857da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'farm_sessions',
        'start_time',
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(),
        existing_nullable=False,
        postgresql_using="start_time::timestamp without time zone"
    )

    op.alter_column(
        'farm_sessions',
        'end_time',
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(),
        nullable=True,
        postgresql_using="end_time::timestamp without time zone"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.alter_column(
        'farm_sessions',
        'end_time',
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(),
        nullable=True
    )
    op.alter_column(
        'farm_sessions',
        'start_time',
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(),
        existing_nullable=False
    )
