"""add icons

Revision ID: c6e9f2673bbd
Revises: 7eff3741a673
Create Date: 2025-01-15 20:42:54.207119

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6e9f2673bbd'
down_revision: Union[str, None] = '7eff3741a673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('icon', sa.String(), nullable=False))
    op.add_column('resources', sa.Column('icon', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'icon')
    op.drop_column('items', 'icon')
    # ### end Alembic commands ###
