"""empty message

Revision ID: cc0e4295a57a
Revises: 709d867cf34e
Create Date: 2025-01-10 21:42:34.509713

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc0e4295a57a'
down_revision: Union[str, None] = '709d867cf34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_objects', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('players', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('players_user_id_fkey', 'players', type_='foreignkey')
    op.drop_column('players', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('players_user_id_fkey', 'players', 'users', ['user_id'], ['telegram_id'])
    op.drop_column('players', 'name')
    op.alter_column('map_objects', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
