"""empty message

Revision ID: e5795c11760d
Revises: be4c199f24d1
Create Date: 2025-01-14 21:19:35.669818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5795c11760d'
down_revision: Union[str, None] = 'be4c199f24d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'slots')
    op.add_column('players', sa.Column('inventory_slots', sa.Integer(), nullable=True))
    from sqlalchemy.sql import table, column, update
    players_table = table(
        'players',
        column('inventory_slots', sa.Integer())
    )
    op.execute(update(players_table).values(inventory_slots=10))
    op.alter_column('players', 'inventory_slots', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'inventory_slots')
    op.add_column('inventories', sa.Column('slots', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
